services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crop-ai-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
   
    volumes:
      - ./backend:/app
      - /app/__pycache__
    restart: unless-stopped
    networks:
      - crop-ai-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: crop-ai-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - crop-ai-network

networks:
  crop-ai-network:
    driver: bridge

volumes:
  backend_data:
